version: '3'

services:
  web:
    build: 
      context: ./
      dockerfile: ./paas/docker/web/Dockerfile
    container_name: pokerphace-web
    ports:
      - '80:80'
    volumes:
      - './:/app'
      - './paas/docker/web/nginx/pokerphace.conf:/etc/nginx/conf.d/pokerphace.conf'
    links:
      - database
    networks:
      - pokerphace-network
  database:
    image: postgres
    container_name: pokerphace-database
    environment:
      POSTGRES_USER: pokerphace
      POSTGRES_PASSWORD: pokerphace
      POSTGRES_DB: pokerphace
    ports:
      - '5432:5432'
    networks:
      - pokerphace-network
networks:
  pokerphace-network:
      driver: bridge