default:
  suites:
    authentication:
      paths:
        - 'test/acceptance/Feature/Authentication'
      contexts:
        - AcceptanceTest\Context\Authentication\GenerateJwtTokenContext
    technical_information:
      paths:
        - 'test/acceptance/Feature/TechnicalInformation'
      contexts:
        - AcceptanceTest\Context\TechnicalInformation\FetchContext